# Game screen constants
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_COLOR = "black"
SCREEN_TITLE = "The Great Pong Game"
PEN_COLOR = "white"
PEN_SIZE = 5
UP = 90

# Paddle constants
PADDLE_COLOR = "white"
PADDLE_SHAPE = "square"
SEGMENT_DIMENSIONS = (20, 20)
PADDLE_SPEED = 20
RIGHT_PADDLE_POSITION = (350, 0)
LEFT_PADDLE_POSITION = (-350, 0)
PADDLE_MAX_Y_POSITION = 240
WIDTH_STRETCH_CONSTANT = 5
LENGTH_STRETCH_CONSTANT = 1

# Ball constants
BALL_COLOR = "white"
BALL_SHAPE = "circle"
BALL_SPEED = 5
BALL_STARTING_ANGLE_RANGE = 45
BALL_BOUNCING_WALL_BORDER = 280
BALL_STARTING_POSITION = (0, 0)
RIGHT = 0
LEFT = 180
BALL_PADDLE_MAX_DISTANCE = 50

# scoreboard constants
PENCOLOR="white"
LEFT_SCOREBOARD_POS = (-120, 260)
RIGHT_SCOREBOARD_POS = (100, 260)
FINAL_SCOREBOARD_LEFT_POS = (-330, 200)
FINAL_SCOREBOARD_RIGHT_POS = (50, 200)
FINAL_SCOREBOARD_STARTING_POS = (0, 0)
FONT = ('Arial', 25, 'bold')
MATCH_POINT = 5

# Net constants
CENTER_LINE_HEIGHT = 12
