# Game screen constants
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_COLOR = "black"
SCREEN_TITLE = "The Great Pong Game"
UP = 90
PEN_COLOR = "white"
PEN_SIZE = 5
CENTER_LINE_HEIGHT = 12

# Paddle constants
PADDLE_COLOR = "white"
SEGMENT_DIMENSIONS = (20, 20)
PADDLE_SPEED = 10
RIGHT_PADDLE_X_POS = 350
LEFT_PADDLE_X_POS = -350
PADDLE_Y_POS = 0
WIDTH_STRETCH_CONSTANT = 5
LENGTH_STRETCH_CONSTANT = 1