# Game screen constants
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_COLOR = "black"
SCREEN_TITLE = "The Great Pong Game"
PEN_COLOR = "white"
PEN_SIZE = 5
CENTER_LINE_HEIGHT = 12
UP = 90

# Paddle constants
PADDLE_COLOR = "white"
PADDLE_SHAPE = "square"
SEGMENT_DIMENSIONS = (20, 20)
PADDLE_SPEED = 20
RIGHT_PADDLE_X_POS = 350
LEFT_PADDLE_X_POS = -350
PADDLE_Y_POS = 0
PADDLE_MAX_Y_POSITION = 240
WIDTH_STRETCH_CONSTANT = 5
LENGTH_STRETCH_CONSTANT = 1

# Ball constants
BALL_COLOR = "white"
BALL_SHAPE = "circle"
BALL_SPEED = 10
BALL_STARTING_ANGLE = 45
BALL_BOUNCING_BORDER = 290
